/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sheetal
 */
public class AddUsre extends javax.swing.JFrame{
 Random ran;
   long first;
     JLabel userid;
     String curdate=new String();
    /**
     * Creates new form AddUsre
     */
    public AddUsre() {
        
        //id creation

        
        
        userIDCreation();
          
        //keyListeners
         
         
         
         initComponents();
       currentdatetime();
       this.setSize(550,460);
       this.setLocation(420,150);
       this.setResizable(false);
       this.setTitle("HMS- AddUser");
       this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cb = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        date = new javax.swing.JLabel();
        dobcal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 102, 102));
        l1.setText("User ID :");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 102, 102));
        l2.setText("User Name :");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(102, 102, 102));
        l3.setText("User Type :");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        l4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(102, 102, 102));
        l4.setText("Sex :");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 200, 50, -1));

        l5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(102, 102, 102));
        l5.setText("DOB :");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, 30));

        l6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l6.setForeground(new java.awt.Color(102, 102, 102));
        l6.setText(" Email :");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 282, 70, 30));

        l7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l7.setForeground(new java.awt.Color(102, 102, 102));
        l7.setText("Contact :");
        getContentPane().add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        l8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l8.setForeground(new java.awt.Color(102, 102, 102));
        l8.setText("Education :");
        getContentPane().add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 119, 180, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setToolTipText("");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 282, 180, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setToolTipText("");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 322, 180, 30));

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10th", "12th", "Graduate", "Post Graduate", "Diploma" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 180, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 80, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText(" ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Add ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 80, 50));

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Receptionist" }));
        getContentPane().add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 180, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 70, 20));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Other");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date.setText(" ");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, -1));
        getContentPane().add(dobcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
                 
                new AdminLog().setVisible(true);
                setVisible(false);
            
                 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         jTextField1.setText("");
         cb.setSelectedItem("");
         dobcal.setDateFormatString(curdate);
         buttonGroup1.clearSelection();
         jTextField5.setText("");
         jTextField6.setText("");
          cb1.setSelectedItem("");
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
                Conn conn = new Conn();
                String checkexistence = "Select * From usersdetails where id='"+userid.getText()+"'";
                ResultSet rs = conn.s.executeQuery(checkexistence);
                if (rs.next()) {
                    
                    
                    JOptionPane.showMessageDialog(null, "User Alraedy Exist With This Id");
                    jTextField1.setText("");
                    cb.setSelectedItem("");
                    dobcal.setDateFormatString(curdate);
                    buttonGroup1.clearSelection();
                    jTextField5.setText("");
                    jTextField6.setText("");
                     cb1.setSelectedItem("");
                             
                    
                    
                    }
                else
                {
                    Pattern patt2 = Pattern.compile("[a-zA-Z0-9][a-zA-Z0-9_.-]*@gmail[.]com");
                    Pattern pattmob = Pattern.compile("(0/91)?[6-9][0-9]{9}");
                    Matcher gmatch = patt2.matcher(jTextField5.getText());
                    Matcher mobmatch = pattmob.matcher(jTextField6.getText());
                     if (jTextField1.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please file all Fields");
                    }else if (cb.getSelectedItem()=="") {
                        JOptionPane.showMessageDialog(null, "Select User Type");
                    } else if (dobcal.isCursorSet()) {
                        JOptionPane.showMessageDialog(null, "Please choose DOB","DOB didn't select",JOptionPane.ERROR_MESSAGE);
                    }
                    else if (jRadioButton1.isSelected()== false && jRadioButton2.isSelected()==false && jRadioButton3.isSelected()==false) {
                        JOptionPane.showMessageDialog(null, "Please select gender" ,"Gender didn't select",JOptionPane.ERROR_MESSAGE);}
                    else if (jTextField5.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please Give Email ID");
                    } else if (jTextField6.getText().trim().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Please give contact number !!",null, JOptionPane.ERROR_MESSAGE);
                    }else if(cb1.getSelectedItem().equals(""))
                    {
                        JOptionPane.showMessageDialog(null, "Select Qualification");
                    }
                    else if (!gmatch.matches()) {
                        JOptionPane.showMessageDialog(null, "Enter mail id in correct format!!", null, JOptionPane.ERROR_MESSAGE);
                        jTextField5.setText("");
                    } 
                     else if (!mobmatch.matches()) {
                        JOptionPane.showMessageDialog(null, "Please enter phone valid contact number !!!!", null, JOptionPane.ERROR_MESSAGE);
                        jTextField6.setText("");
                    }else
                     {
                        Date Subdate =dobcal.getDate();
                        Conn con1 = new Conn();
                       String j=jTextField1.getText();
                       String k=(String)cb.getSelectedItem();
                       String l=new String();
                       String m=DateFormat.getDateInstance().format(Subdate);
                       String n=jTextField5.getText();
                       String o=jTextField6.getText();
                       String Usid = userid.getText();
                       String dt = date.getText();
                       String p = (String)cb1.getSelectedItem();
                       if(jRadioButton1.isSelected()){
                           l=jRadioButton1.getText();
                       }else if(jRadioButton2.isSelected()){
                           l=jRadioButton2.getText();
                       }
                        else if(jRadioButton3.isSelected()){
                           l=jRadioButton3.getText();
                       }
                         
                       String q1 ="Insert into usersdetails values('"+Usid+"','"+k+"','"+j+"','"+l+"','"+m+"','"+o+"','"+n+"','"+dt+"','"+p+"')";
                       con1.s.executeUpdate(q1);
                       Random passward = new Random();
                       long pass=(passward.nextLong() % 9000000L) + 1000000L;
                       long pass8=Math.abs(pass);
                       String q2 ="Insert into users values('"+Usid+"','"+pass8+"')";
                       con1.s.executeUpdate(q2);
                       JOptionPane.showMessageDialog(null, "Your User ID is : "+Usid+" and Passward is:"+pass8, null, JOptionPane.INFORMATION_MESSAGE);
                       
                       new AdminLog().setVisible(true);
                       setVisible(false);
                       
                     }
                     
                 }
        }
        catch(Exception ae)
        {
            ae.getStackTrace();
            System.out.println(ae);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUsre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUsre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUsre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUsre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new AddUsre().setVisible(true);
            }
        });
    }
    private void currentdatetime() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        curdate =dtf.format(now);
        date.setText("Date: "+dtf.format(now));

    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser dobcal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    // End of variables declaration//GEN-END:variables

    private void userIDCreation() {
        
         ran = new Random();
        long first4 = (ran.nextLong() % 900000L) + 100000L;
        first = Math.abs(first4);
        userid = new JLabel();
        userid = new JLabel();
        userid.setFont(new Font("System",Font.BOLD,18));
        userid.setText(""+first);
        userid.setBounds(247, 79, 160, 20);
        this.add(userid);
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/hospitalmanagementsystem/WinIcon.png")));
    }
 }
